config/routes.rb
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do

  # Jumpstart views
  if Rails.env.development? || Rails.env.test?
    mount Jumpstart::Engine, at: '/jumpstart'
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Administrate
  authenticated :user, lambda { |u| u.admin? } do
    namespace :admin do
      if defined?(Sidekiq)
        require 'sidekiq/web'
        mount Sidekiq::Web => '/sidekiq'
      end

      resources :announcements
      resources :users
      namespace :user do
        resources :connected_accounts
      end
      resources :teams
      resources :team_members
      resources :plans
      namespace :pay do
        resources :charges
        resources :subscriptions
      end

      root to: "dashboard#show"
    end
  end

  # API routes
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resource :me, controller: :me
      resources :teams
      resources :users
    end
  end

  # User account
  devise_for :users,
             controllers: {
               masquerades: 'jumpstart/masquerades',
               omniauth_callbacks: 'users/omniauth_callbacks',
               registrations: 'users/registrations',
             }

  resources :announcements, only: [:index]
  resources :api_tokens
  resources :teams do
    member do
      patch :switch
    end

    resources :team_members, path: :members
  end

  # Payments
  resource :card
  resource :subscription do
    patch :info
    patch :resume
  end
  resources :charges
  namespace :account do
    resource :password
  end

  namespace :users do
    resources :mentions, only: [:index]
  end
  namespace :user, module: :users do
    resources :connected_accounts
  end

  scope controller: :static do
    get :about
    get :terms
    get :privacy
    get :pricing
  end

  match "/404", via: :all, to: "errors#not_found"
  match "/500", via: :all, to: "errors#internal_server_error"

  authenticated :user do
    root to: "dashboard#show", as: :user_root
  end

  # Public marketing homepage
  root to: "static#index"
end

app/models/team_member.rb
# == Schema Information
#
# Table name: team_members
#
#  id         :bigint(8)        not null, primary key
#  roles      :jsonb            not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  team_id    :bigint(8)
#  user_id    :bigint(8)
#
# Indexes
#
#  index_team_members_on_team_id  (team_id)
#  index_team_members_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (team_id => teams.id)
#  fk_rails_...  (user_id => users.id)
#

class TeamMember < ApplicationRecord
  belongs_to :team
  belongs_to :user

  # Add team roles to this line
  ROLES = [:admin]

  # Store the roles in the roles json column and cast to booleans
  store_accessor :roles, *ROLES

  # Cast roles to/from booleans
  ROLES.each do |role|
    define_method(:"#{role}=") { |value| super ActiveRecord::Type::Boolean.new.deserialize(value) }
    define_method(:"#{role}")  { ActiveRecord::Type::Boolean.new.deserialize super() }
    define_method(:"#{role}?") { send(role) }
  end
end

app/controllers/admin/team_members_controller.rb
module Admin
  class TeamMembersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_team
  before_action :require_non_personal_team!
  before_action :set_team_member, only: [:edit, :update, :destroy, :switch]

  # GET /teams
  def index
    redirect_to @team
  end

  # GET /team_members/1
  def show
    redirect_to @team
  end

  # GET /team_members/new
  def new
    @team_member = TeamMember.new
  end

  # GET /team_members/1/edit
  def edit
  end

  # POST /team_members
  def create
    user = User.invite!({ name: params[:name], email: params[:email] }, current_user)
    if user.persisted?
      @team.team_members.create(user: user, admin: params[:admin])
      redirect_to @team, notice: 'Team member was successfully added.'
    else
      render :new
    end
  end

  # PATCH/PUT /team_members/1
  def update
    if @team_member.update(team_member_params)
      redirect_to @team, notice: 'Team member was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /team_members/1
  def destroy
    @team_member.destroy
    redirect_to @team, notice: 'Team member was successfully removed.'
  end

  private
    def set_team
      @team = current_user.teams.find(params[:team_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_team_member
      @team_member = @team.team_members.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def team_member_params
      attrs = [:user_id] + TeamMember.local_stored_attributes[:roles]
      params.require(:team_member).permit(*attrs)
    end

    def require_non_personal_team!
      redirect_to teams_path if @team.personal?
    end
end

app/views/team_members/_form.html.erb
<%= form_with(model: [@team, team_member]) do |form| %>
  <%= render "shared/error_messages", resource: form.object %>

  <h5 class="mb-2">Roles</h5>
  <div class="form-group">
    <% TeamMember::ROLES.each do |role| %>
      <label>
        <%= form.check_box role, class: "mr-1" %>
        <%= role.to_s.humanize %>
      </label>
    <% end %>
  </div>

  <div class="form-group flex justify-between">
    <%= form.button class: "btn btn-primary" %>

    <% if form.object.persisted? %>
      <%= link_to 'Delete', team_team_member_path(@team, form.object), class: "btn btn-danger outline", method: :delete, remote: true, data: { confirm: "Are you sure?" } %>
    <% end %>
  </div>
<% end %>

app/views/team_members/edit.html.erb
<div class="flex flex-wrap my-4 lg:px-4">
  <div class="lg:w-1/4 w-full p-4">
    <%= render partial: "shared/account_navbar" %>
  </div>

  <div class="lg:w-3/4 w-full p-4">
    <div class="flex items-center">
      <%= team_avatar @team, class: "rounded-full mr-4 h-12 w-12" %>
      <h1 class="h2"><%= @team.name %></h1>
    </div>

    <p class="my-4">Editing team permissions for <%= @team_member.user.name || @team_member.user.email %>.</p>

    <%= render "form", team_member: @team_member %>
  </div>
</div>

app/views/team_members/new.html.erb
<div class="flex flex-wrap my-4 lg:px-4">
  <div class="lg:w-1/4 w-full p-4">
    <%= render partial: "shared/account_navbar" %>
  </div>

  <div class="lg:w-3/4 w-full p-4">
    <div class="text-sm text-gray-600 mb-5">
      <%= link_to "All Teams", teams_path, class: "hover:text-black" %>
      <%= render_svg "icons/cheveron-right", styles: "fill-current icon-sm text-gray-600 inline-block" %>
      <%= link_to @team.name, @team, class: "hover:text-black" %>
      <%= render_svg "icons/cheveron-right", styles: "fill-current icon-sm text-gray-600 inline-block" %>
      Team Members
    </div>

    <div class="lg:p-10 p-4 bg-white rounded-lg border border-gray-300">

      <div class="flex items-center">
        <%= team_avatar @team, class: "rounded-full mr-4 h-12 w-12" %>
        <h1 class="h2"><%= @team.name %></h1>
      </div>

      <p class="my-4">Invite a user to your join team.</p>

      <%= form_with(url: team_team_members_path(@team)) do |form| %>
        <%#= render "shared/error_messages", resource: form.object %>

        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: "form-control", required: true, placeholder: "Full name" %>
        </div>

        <div class="form-group">
          <%= form.label :email %>
          <%= form.email_field :email, class: "form-control", required: true, placeholder: "example@domain.com" %>
        </div>

        <h5 class="mb-2">Roles</h5>
        <div class="form-group">
          <% TeamMember.local_stored_attributes[:roles].each do |role| %>
            <label>
              <%= form.check_box role, class: "mr-1" %>
              <%= role.to_s.humanize %>
            </label>
          <% end %>
        </div>

        <div class="form-group">
          <%= form.button "Send invitation", class: "btn btn-primary" %>
          <%= link_to "Cancel", @team, class: "btn btn-link" %>
        </div>
      <% end %>
    </div>
  </div>
</div>