config/routes.rb
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do

  # Jumpstart views
  if Rails.env.development? || Rails.env.test?
    mount Jumpstart::Engine, at: '/jumpstart'
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Administrate
  authenticated :user, lambda { |u| u.admin? } do
    namespace :admin do
      if defined?(Sidekiq)
        require 'sidekiq/web'
        mount Sidekiq::Web => '/sidekiq'
      end

      resources :announcements
      resources :users
      namespace :user do
        resources :connected_accounts
      end
      resources :teams
      resources :team_members
      resources :plans
      namespace :pay do
        resources :charges
        resources :subscriptions
      end

      root to: "dashboard#show"
    end
  end

  # API routes
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resource :me, controller: :me
      resources :teams
      resources :users
    end
  end

  # User account
  devise_for :users,
             controllers: {
               masquerades: 'jumpstart/masquerades',
               omniauth_callbacks: 'users/omniauth_callbacks',
               registrations: 'users/registrations',
             }

  resources :announcements, only: [:index]
  resources :api_tokens
  resources :teams do
    member do
      patch :switch
    end

    resources :team_members, path: :members
  end

  # Payments
  resource :card
  resource :subscription do
    patch :info
    patch :resume
  end
  resources :charges
  namespace :account do
    resource :password
  end

  namespace :users do
    resources :mentions, only: [:index]
  end
  namespace :user, module: :users do
    resources :connected_accounts
  end

  scope controller: :static do
    get :about
    get :terms
    get :privacy
    get :pricing
  end

  match "/404", via: :all, to: "errors#not_found"
  match "/500", via: :all, to: "errors#internal_server_error"

  authenticated :user do
    root to: "dashboard#show", as: :user_root
  end

  # Public marketing homepage
  root to: "static#index"
end

app/views/shared/_account_navbar.html.erb
<div class="bg-white border border-gray-300 rounded">
  <%= nav_link_to "Profile", edit_user_registration_path,   class: "block no-underline p-3 px-6 rounded-t", active_class: "bg-primary-500 text-white hover:text-white", inactive_class: "text-gray-700 hover:text-gray-700 hover:bg-gray-100" %>
  <%= nav_link_to "Password", edit_account_password_path,   class: "block no-underline p-3 px-6", active_class: "bg-primary-500 text-white hover:text-white", inactive_class: "text-gray-700 hover:text-gray-700 hover:bg-gray-100" %>
  <%= nav_link_to "Accounts", user_connected_accounts_path, class: "block no-underline p-3 px-6", active_class: "bg-primary-500 text-white hover:text-white", inactive_class: "text-gray-700 hover:text-gray-700 hover:bg-gray-100" if Devise.omniauth_configs.any? %>
  <%= nav_link_to "Billing", subscription_path,             class: "block no-underline p-3 px-6", active_class: "bg-primary-500 text-white hover:text-white", inactive_class: "text-gray-700 hover:text-gray-700 hover:bg-gray-100", starts_with: ["/subscription", "/card"] if Jumpstart.config.payments_enabled? %>
  <%= nav_link_to "Teams", teams_path,                      class: "block no-underline p-3 px-6 rounded-b", active_class: "bg-primary-500 text-white hover:text-white", inactive_class: "text-gray-700 hover:text-gray-700 hover:bg-gray-100", starts_with: "/team" %>
  <%= nav_link_to "API", api_tokens_path,                   class: "block no-underline p-3 px-6 rounded-b", active_class: "bg-primary-500 text-white hover:text-white", inactive_class: "text-gray-700 hover:text-gray-700 hover:bg-gray-100" %>
</div>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-error mb-6" role="alert">
    <div class="flex items-start justify-start">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" class="fill-current icon mr-4 mt-1 flex-no-shrink" role="img" aria-labelledby="f1yx75u7nv0lvn6ck4z10w7lksjmk2f"><title id="f1yx75u7nv0lvn6ck4z10w7lksjmk2f">Icons/close outline</title><path d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zm1.41-1.41A8 8 0 1 0 15.66 4.34 8 8 0 0 0 4.34 15.66zm9.9-8.49L11.41 10l2.83 2.83-1.41 1.41L10 11.41l-2.83 2.83-1.41-1.41L8.59 10 5.76 7.17l1.41-1.41L10 8.59l2.83-2.83 1.41 1.41z"></path></svg>

      <div>
        <h4 class="font-black text-sm uppercase tracking">
          <%= I18n.t("errors.messages.not_saved", count: resource.errors.count, resource: resource.class.model_name.human.downcase) %>
        </h4>
        <ul>
          <% resource.errors.full_messages.each do |message| %>
            <li><%= message %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_favicons.html.erb
<%= favicon_link_tag "favicon/apple-icon-57x57.png", rel: "apple-touch-icon", sizes: "57x57" %>
<%= favicon_link_tag "favicon/apple-icon-60x60.png", rel: "apple-touch-icon", sizes: "60x60" %>
<%= favicon_link_tag "favicon/apple-icon-72x72.png", rel: "apple-touch-icon", sizes: "72x72" %>
<%= favicon_link_tag "favicon/apple-icon-76x76.png", rel: "apple-touch-icon", sizes: "76x76" %>
<%= favicon_link_tag "favicon/apple-icon-114x114.png", rel: "apple-touch-icon", sizes: "114x114" %>
<%= favicon_link_tag "favicon/apple-icon-152x152.png", rel: "apple-touch-icon", sizes: "152x152" %>
<%= favicon_link_tag "favicon/apple-icon-180x180.png", rel: "apple-touch-icon", sizes: "180x180" %>
<%= favicon_link_tag "favicon/android-icon-192x192.png", type: "image/png", sizes: "192x192" %>
<%= favicon_link_tag "favicon/favicon-32x32.png", type: "image/png", rel: "icon", sizes: "32x32" %>
<%= favicon_link_tag "favicon/favicon-96x96.png", type: "image/png", rel: "icon", sizes: "96x96" %>
<%= favicon_link_tag "favicon/favicon-16x16.png", type: "image/png", rel: "icon", sizes: "16x16" %>
<%= favicon_link_tag "favicon/favicon-16x16.png", type: "image/ico", rel: "icon", sizes: "16x16" %>
<%= favicon_link_tag "favicon/manifest.json", rel: "manifest" %>
<%= content_tag :meta, nil, name: "msapplication-TileColor", content: "#ffffff"  %>
<%= content_tag :meta, nil, name: "msapplication-TileImage", content: "#{asset_path('/favicon/ms-icon-144x144.png')}"  %>
<%= content_tag :meta, nil, name: "theme-color", content: "#ffffff"  %>

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="flex items-center bg-blue-100 text-blue-600 text-sm justify-center font-bold px-4 py-3" role="alert">
    <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/></svg>
    <p><%= notice %></p>
  </div>
<% end %>

<% if alert %>
  <div class="flex items-center bg-orange-100 text-orange-600 justify-center text-sm font-bold px-4 py-3" role="alert">
    <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/></svg>
    <p><%= alert %></p>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="bg-white border-t border-gray-400 py-1 lg:px-6 px-2 w-full lg:h-16 h-auto">
  <div class="text-sm flex flex-col-reverse p-4 lg:flex-row lg:justify-between lg:p-0">
    <div class="flex items-center justify-center">
      <%= link_to root_path do %>
        <%= render_svg 'jumpstart-mark', styles: "fill-current text-gray-600 hover:text-gray-700" %>
      <% end %>
      <div class="ml-4 text-gray-700">© <%= Date.current.year %> <%= Jumpstart.config.business_name %></div>
    </div>

    <div class="flex flex-col items-center lg:flex-row">
      <%= link_to "About Us", about_path, class: "text-gray-700 no-underline block lg:my-0 my-2 lg:px-4" %>
      <%= link_to "Privacy Policy", privacy_path, class: "text-gray-700 hover:text-gray-800 no-underline block lg:my-0 my-2 lg:px-4" %>
      <%= link_to "Terms of Service", terms_path, class: "text-gray-700 hover:text-gray-800 no-underline block lg:my-0 my-2 lg:pl-4" %>
    </div>
  </div>
</div>

app/views/shared/_left_nav.html.erb
<%# Place any links for the LEFT side of the nav bar here. Be sure to add class: "nav-link" to each item for proper spacing. %>

app/views/shared/_navbar.html.erb
<% if user_masquerade? %>
  <div class="bg-blue-600 text-blue-200 text-sm text-center font-brand-semibold px-4 py-3" role="alert">
    You're logged in as <b>User #<%= current_user.id %></b> (<%= current_user.email %>)</b>
    <%= link_to "Logout", back_masquerade_path(current_user), class: "text-blue-100 hover:no-underline font-semibold underline" %>
  </div>
<% end %>

<nav class="flex items-center justify-between flex-wrap bg-white border-b px-4 py-2" data-controller="toggle">
  <div class="flex items-center flex-shrink-0 mr-6">
    <%= link_to root_path do %>
      <%= render_svg "logo", styles: "fill-current text-gray-700 hover:text-gray-800" %>
      <span class="sr-only"><%= Jumpstart.config.application_name %></span>
    <% end %>
  </div>

  <div class="block lg:hidden">
    <button type="button" id="sidebar-open" class="flex px-6 items-center lg:hidden text-gray-500 focus:outline-none focus:text-gray-700" data-action="click->toggle#toggle touch->toggle#toggle">
      <svg class="fill-current w-4 h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"></path></svg>
    </button>
  </div>

  <div class="w-full block flex-grow hidden lg:flex lg:items-center lg:w-auto" data-target="toggle.toggleable" >
    <div class="text-sm lg:flex-grow">
      <%= render "shared/left_nav" %>
    </div>

    <div class="text-sm">
      <%= render "shared/right_nav" %>

      <% if user_signed_in? %>
        <div class="z-10 inline-flex items-center align-middle leading-none rounded no-underline text-gray-700 hover:text-gray-800 hover:bg-white">
          <div class="relative" data-controller="dropdown">
            <div data-action="click->dropdown#toggle click@window->dropdown#hide touch->dropdown#toggle touch@window->dropdown#hide" role="button" class="inline-block select-none">
              <span class="appearance-none flex items-center inline-block text-gray-700">
                <%= team_avatar current_team, include_user: true, class: "rounded-full h-8 w-8" %>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" width="1rem" height="1rem" class="h-4 w-4"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"></path></svg>
              </span>
            </div>
            <div data-target="dropdown.menu" class="lg:absolute lg:right-0 mt-2 hidden z-20">
              <div class="bg-white shadow rounded border overflow-hidden">
                <%= link_to current_team, class: 'border-b text-sm no-underline block px-6 py-3 text-gray-800 bg-white hover:bg-gray-300 whitespace-no-wrap' do %>
                  Signed in as <strong><%= current_team.name %></strong>
                <% end %>

                <%= link_to 'Profile',  edit_user_registration_path, class: 'no-underline block px-6 py-3 text-sm text-gray-800 bg-white hover:bg-gray-300 whitespace-no-wrap' %>
                <%= link_to 'Password', account_password_path, class: 'no-underline block px-6 py-3 text-sm text-gray-800 bg-white  hover:bg-gray-300 whitespace-no-wrap' %>
                <%= link_to 'Accounts', user_connected_accounts_path, class: 'no-underline block px-6 py-3 text-sm text-gray-800 bg-white  hover:bg-gray-300 whitespace-no-wrap' if Devise.omniauth_configs.any? %>
                <%= link_to 'Billing',  subscription_path, class: 'no-underline block px-6 py-3 text-sm text-gray-800 bg-white  hover:bg-gray-300 whitespace-no-wrap' if Jumpstart.config.payments_enabled? %>
                <%#= link_to 'API',  subscription_path, class: 'no-underline block px-6 py-3 text-sm text-gray-800 bg-white  hover:bg-gray-300 whitespace-no-wrap' if Jumpstart.config.payments_enabled? %>

                <!--
                <div class="border-t px-6 py-3 text-gray-800 bg-white font-bold text-xs uppercase">Teams</div>
                -->
                <%= link_to "Teams", teams_path, class: 'border-t text-xs uppercase font-bold text-gray-800 no-underline block px-6 py-3 bg-white hover:bg-gray-300 whitespace-no-wrap' %>
                <% current_user.teams.each do |team| %>
                  <%= link_to team.name, switch_team_path(team), remote: true, method: :patch, class: 'no-underline block px-6 py-3 text-sm text-gray-800 bg-white hover:bg-gray-300 whitespace-no-wrap' %>
                <% end %>


                <% if current_user.admin? %>
                  <div class="border-t px-6 py-3 text-gray-800 bg-white font-bold text-xs uppercase">Admin</div>
                  <%= link_to 'Dashboard', admin_root_path, class: 'no-underline block px-6 py-3 text-sm text-gray-800 bg-white  hover:bg-gray-300 whitespace-no-wrap', data: { turbolinks: false } %>
                  <%= link_to 'Sidekiq', admin_sidekiq_web_path, class: 'no-underline block px-6 py-3 text-sm text-gray-800 bg-white  hover:bg-gray-300 whitespace-no-wrap', target: :_blank, data: { turbolinks: false } if defined?(::Sidekiq) %>
                <% end %>

                <% if Rails.env.development? %>
                  <div class="border-t px-6 py-3 text-gray-800 bg-white font-bold text-xs uppercase">Development</div>
                  <%= link_to 'Jumpstart Config', jumpstart_path, class: 'no-underline block px-6 py-3 text-sm text-gray-800 bg-white  hover:bg-gray-300 whitespace-no-wrap', data: { turbolinks: false } %>
                  <%= link_to 'Jumpstart Docs', jumpstart.docs_path, class: 'no-underline block px-6 py-3 text-sm text-gray-800 bg-white  hover:bg-gray-300 whitespace-no-wrap', target: :_blank, data: { turbolinks: false } %>
                  <%= link_to 'Letter Opener', letter_opener_web_path, class: 'no-underline block px-6 py-3 text-sm text-gray-800 bg-white  hover:bg-gray-300 whitespace-no-wrap', target: :_blank, data: { turbolinks: false } %>
                <% end %>

                <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'no-underline block px-6 py-3 border-t text-sm text-gray-800 bg-white hover:bg-gray-300 whitespace-no-wrap' %>
              </div>
            </div>
          </div>
        </div>

      <% else %>
        <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
        <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary' %>
      <% end %>

    </div>
  </div>
</nav>

app/views/shared/_payments_dependencies.html.erb
<% if Jumpstart.config.stripe? %>
  <%= javascript_include_tag 'https://js.stripe.com/v3/' %>
<% end %>

<% if Jumpstart.config.braintree? || Jumpstart.config.paypal? %>
  <%= javascript_include_tag 'https://js.braintreegateway.com/web/dropin/1.13.0/js/dropin.min.js' %>
<% end %>

<%# https://developer.paypal.com/docs/checkout/how-to/braintree-integration/#1-set-up-your-client %>
<% if Jumpstart.config.paypal? %>
  <!-- Load PayPal's checkout.js Library. -->
  <script src="https://www.paypalobjects.com/api/checkout.js" data-version-4 log-level="warn"></script>

  <!-- Load the client component. -->
  <script src="https://js.braintreegateway.com/web/3.37.0/js/client.min.js"></script>

  <!-- Load the PayPal Checkout component. -->
  <script src="https://js.braintreegateway.com/web/3.37.0/js/paypal-checkout.min.js"></script>
<% end %>

app/views/shared/_right_nav.html.erb
<%# Place any links for the RIGHT side of the nav bar here. Be sure to add class: "nav-link" to each item for proper spacing. %>

<%= nav_link_to "Pricing", pricing_path, class: "nav-link" if Jumpstart.config.payments_enabled? && not_subscribed? %>
<%= nav_link_to content_tag(:span, "What's New"), announcements_path, class: ["nav-link", unread_announcements_class(current_user)] %>