config/routes.rb
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do

  # Jumpstart views
  if Rails.env.development? || Rails.env.test?
    mount Jumpstart::Engine, at: '/jumpstart'
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Administrate
  authenticated :user, lambda { |u| u.admin? } do
    namespace :admin do
      if defined?(Sidekiq)
        require 'sidekiq/web'
        mount Sidekiq::Web => '/sidekiq'
      end

      resources :announcements
      resources :users
      namespace :user do
        resources :connected_accounts
      end
      resources :teams
      resources :team_members
      resources :plans
      namespace :pay do
        resources :charges
        resources :subscriptions
      end

      root to: "dashboard#show"
    end
  end

  # API routes
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resource :me, controller: :me
      resources :teams
      resources :users
    end
  end

  # User account
  devise_for :users,
             controllers: {
               masquerades: 'jumpstart/masquerades',
               omniauth_callbacks: 'users/omniauth_callbacks',
               registrations: 'users/registrations',
             }

  resources :announcements, only: [:index]
  resources :api_tokens
  resources :teams do
    member do
      patch :switch
    end

    resources :team_members, path: :members
  end

  # Payments
  resource :card
  resource :subscription do
    patch :info
    patch :resume
  end
  resources :charges
  namespace :account do
    resource :password
  end

  namespace :users do
    resources :mentions, only: [:index]
  end
  namespace :user, module: :users do
    resources :connected_accounts
  end

  scope controller: :static do
    get :about
    get :terms
    get :privacy
    get :pricing
  end

  match "/404", via: :all, to: "errors#not_found"
  match "/500", via: :all, to: "errors#internal_server_error"

  authenticated :user do
    root to: "dashboard#show", as: :user_root
  end

  # Public marketing homepage
  root to: "static#index"
end

app/controllers/admin/pay/subscriptions_controller.rb
module Admin
  class Pay::SubscriptionsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Pay::Subscription.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Pay::Subscription.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_team, :require_payments_enabled
  before_action :set_plan, only: [:new]
  before_action :set_subscription, only: [:edit, :update]

  def show
  end

  def new
  end

  def create
    current_team.assign_attributes(subscription_params)

    # Get the Stripe or Braintree specific ID
    @plan = Plan.find(current_team.plan)
    processor_id = @plan.processor_id(current_team.processor)

    current_team.subscribe(plan: processor_id)

    redirect_to root_path
  rescue Pay::Error => e
    flash[:alert] = e.message
    render :new
  end

  def edit; end

  def update
    current_team.assign_attributes(subscription_params)

    # Get the Stripe or Braintree specific ID
    @plan = Plan.find(current_team.plan)
    processor_id = @plan.processor_id(current_team.processor)

    @subscription.swap(processor_id)
    redirect_to subscription_path
  rescue Pay::Error => e
    flash[:alert] = e.message
    render :edit
  end

  def resume
    current_team.subscription.resume
    redirect_to subscription_path, notice: "Your subscription has been resumed."
  rescue Pay::Error => e
    flash[:alert] = e.message
    render :show
  end

  def destroy
    current_team.subscription.cancel

    # Optionally, you can cancel immediately
    # current_team.subscription.cancel_now!

    redirect_to subscription_path
  rescue Pay::Error => e
    flash[:alert] = e.message
    render :show
  end

  def info
    current_team.update(subscription_params)
    redirect_to subscription_path, notice: "Extra billing info saved sucessfully."
  end

  private

  def subscription_params
    params.require(:team).permit(:card_token, :plan, :processor, :extra_billing_info)
  end

  def require_team
    redirect_to new_user_registration_path unless current_team
  end

  def require_payments_enabled
    return if Jumpstart.config.payments_enabled?
    flash[:alert] = "Jumpstart must be configured for payments before you can manage subscriptions."
    redirect_back(fallback_location: root_path)
  end

  def set_plan
    @plan = Plan.find_by(id: params[:plan])
    redirect_to pricing_path if @plan.nil?
  end

  def set_subscription
    @subscription = current_team.subscription
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
  def braintree_env
    Rails.env.production? ? 'production' : 'sandbox'
  end

  def payment_method_details(object)
    if object.paypal?
      "#{object.card_type} #{object.card_last4}"
    else
      "#{object.card_type} ending in #{object.card_last4}"
    end
  end
end

app/views/subscriptions/_plan.html.erb
<div class="lg:w-1/3 w-full text-center p-8 border shadow m-4 rounded-lg bg-white">
  <h5><%= plan.name %></h5>
  <div>
    <sup class="text-xl">$</sup>
    <span class="text-4xl"><%= plan.amount / 100 %></span>
    <span class="text-lg">/ <%= plan.interval %></span>
  </div>

  <div class="my-2 text-center">
    <% Array.wrap(plan.features).each do |plan_feature| %>
      <p class="mb-4"><%= plan_feature %></p>
    <% end %>
  </div>

  <%# Yield for custom actions at the bottom %>
  <%= yield %>
</div>

app/views/subscriptions/edit.html.erb
<% if current_team.subscription.on_trial? %>
  <div class="flex justify-center items-center bg-orange-200 text-orange-600 text-sm font-bold px-4 py-3 mb-4" role="alert">
    <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/></svg>
    <p>Your trial ends in <%= time_ago_in_words current_team.subscription.trial_ends_at %>.</p>
  </div>
<% end %>

<div class="container m-auto my-10">
  <div class="flex flex-wrap justify-center">
    <div class="text-center">
      <h1>Change Your Plan</h1>
      <p class="text-xl">Simple, straightforward pricing to get your online business up and running</p>
    </div>
  </div>

  <div data-controller="pricing" data-current="monthly" data-pricing-plans-class="flex hidden" data-pricing-interval-class="bg-white text-black" class="flex flex-wrap items-center justify-center">

    <div data-target="pricing.toggle" class="inline-block rounded-full bg-tertiary-500 py-2 px-1 text-white my-8">
      <a data-action="click->pricing#switch" data-target="pricing.monthlyToggle" data-show="monthly" class="cursor-pointer py-2 px-4 bg-white rounded-full text-black">Monthly</a>
      <a data-action="click->pricing#switch" data-target="pricing.yearlyToggle" data-show="yearly" class="cursor-pointer py-2 px-4 rounded-full"> Yearly</a>
    </div>

    <div class="w-full lg:px-0 px-2">
      <div data-target="pricing.monthlyPlans" class="flex flex-wrap items-center justify-center -mx-4">
        <% Plan.monthly.each do |plan| %>
          <%= render layout: "subscriptions/plan", locals: { plan: plan } do %>
            <% if @subscription.plan == plan %>
              <div class="btn btn-white">Current Plan</div>
            <% else %>
              <%= form_with model: current_team, url: subscription_url do |f| %>
                <%= f.hidden_field :plan, value: plan.id %>
                <%= f.button 'Change Plan', class: "btn btn-tertiary", data: { disable_with: "Processing..." } %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>

      <div data-target="pricing.yearlyPlans" class="hidden flex-wrap items-center justify-center -mx-4">
        <% Plan.yearly.each do |plan| %>
          <%= render layout: "subscriptions/plan", locals: { plan: plan } do %>
            <% if @subscription.plan == plan %>
              <div class="btn btn-white">Current Plan</div>
            <% else %>
              <%= form_with model: current_team, url: subscription_url do |f| %>
                <%= f.hidden_field :plan, value: plan.id %>
                <%= f.button 'Change Plan', class: "btn btn-tertiary", data: { disable_with: "Processing..." } %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/subscriptions/new.html.erb
<div class="shadow-lg rounded-lg flex flex-col sm:flex-row lg:w-1/2 mx-auto my-8 bg-white">
  <div class="sm:w-2/3 p-8">
    <h1>Checkout</h1>

    <hr class="border-b my-8" />

    <div class="flex items-center my-8">
      <%= team_avatar current_team, class: "h-10 w-10 rounded-full mr-4" %>
      <h4><%= current_team.name %></h4>
    </div>

    <div data-controller="toggle">
      <% if current_team.card_last4? %>
        <div data-target="toggle.toggleable">
          <div class="flex mb-8">
            <div class="flex-1">
              <label>Payment Method</label>
              <i class="fab fa-cc-<%= current_team.card_type.downcase %> text-gray-700"></i> <%= payment_method_details(current_team) %>
            </div>
            <%= link_to "Change", "#", class: "text-primary text-sm mt-6", data: { action: "click->toggle#toggle" } %>
          </div>

          <%= form_with model: current_team, url: subscription_url, method: :post do |f| %>
            <%= f.hidden_field :plan, value: @plan.id if @plan.present? %>
            <%= f.button 'Subscribe', id: 'submit-button', class: "btn btn-primary", data: { action: "click->stripe#submit", disable_with: disable_with("Processing...") } %>
          <% end %>
        </div>
      <% end %>

      <%= content_tag :div, class: ("hidden" if current_team.card_last4?), data: { target: "toggle.toggleable" } do %>
        <%= render 'subscriptions/forms/stripe'    if Jumpstart.config.stripe? %>
        <%= render 'subscriptions/forms/braintree' if Jumpstart.config.braintree? %>
        <%= render 'subscriptions/forms/paypal'    if Jumpstart.config.paypal? %>
      <% end %>
    </div>

    <div class="text-sm text-center mt-8">
      <%= render_svg "icons/question", styles: "fill-current text-gray-500 w-4 h-4 inline-block" %>
      Need any help? <span class="text-gray-600">Don't hesitate to <%= mail_to Jumpstart.config.support_email, "contact support", subject: "I have a question about #{Jumpstart.config.application_name}", class: "text-gray-800 underline" %>.</span>
    </div>
  </div>

  <div class="sm:w-1/3 p-8 bg-blue-700 text-white rounded-b-lg sm:rounded-b-none sm:rounded-r-lg">
    <div class="text-lg"><%= @plan.name %></div>

    <div>
      <sup class="text-xl">$</sup>
      <span class="text-5xl"><%= @plan.amount / 100 %></span>
      <span class="text-lg">/ <%= @plan.interval %></span>
    </div>
    <div>Automatically renews<br/> after 1 <%= @plan.interval %></div>

    <br />

    <% @plan.features.each do |plan_feature| %>
      <div class="mb-2"><i class="far fa-check-circle text-blue-400"></i> <%= plan_feature %></div>
    <% end %>

    <hr class="my-8 border-b border-blue-600" />

    <div class="mb-1">I've never found anything easier to use than <%= Jumpstart.config.application_name %>!</div>
    <div class="flex items-center pt-2">
      <img class="block h-8 rounded-full mx-auto mb-4 sm:mb-0 sm:mr-4 sm:ml-0" src="https://avatars1.githubusercontent.com/u/67093?s=40&v=4" alt="">
      <p class="leading-tight">Chris Oliver</p>
    </div>
  </div>
</div>

app/views/subscriptions/show.html.erb
<div class="flex flex-wrap my-4 lg:px-4">
  <div class="lg:w-1/4 w-full p-4">
    <%= render partial: "shared/account_navbar" %>
  </div>

  <div class="lg:w-3/4 w-full p-4">
    <div class="lg:p-10 p-4 bg-white rounded-lg border border-gray-300">
      <h1 class="h2 mb-2">Billing</h2>

      <h3>Current Plan</h3>

      <% if current_team.subscription && current_team.subscription.on_trial? %>
        <div class="flex items-center bg-orange-200 text-orange-600 text-sm font-bold px-4 py-3 my-4" role="alert">
          <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/></svg>
          <p>Your trial ends in <%= time_ago_in_words current_team.subscription.trial_ends_at %>.</p>
        </div>
      <% end %>

      <% if current_team.subscription && current_team.subscription.cancelled? %>
        <% if current_team.subscription.on_grace_period? %>
          <div class="flex">
            <div class="flex-1">
              Your subscription ends <strong><%= current_team.subscription.ends_at.strftime("%B %d, %Y") %></strong>
            </div>

            <div>
              <%= form_for current_team, url: resume_subscription_url, method: :patch do |f| %>
                <%= f.button 'Resume Subscription', class: "btn btn-gray", data: { disable_with: disable_with("Resuming...") } %>
              <% end %>
            </div>
          </div>

        <% else %>
          <p>Your subscription has ended. Would you like to <%= link_to "resubscribe", new_subscription_path, class: "underline text-blue-500" %>?</p>
        <% end %>

      <% elsif current_team.subscription && current_team.subscription.active? %>

        <div class="flex">
          <div class="flex-1">
            <div>You are currently subscribed to the <strong><%= current_team.subscription.plan.name %></strong> plan.</div>
          </div>
          <div>
            <%= link_to "Change my plan", edit_subscription_path, class: "btn btn-link text-gray-700" %>
          </div>
        </div>
      <% else %>
        <div class="flex">
          <div class="flex-1 text-gray-700">You are not currently subscribed.</div>
          <div><%= link_to "Choose a plan", pricing_path, class: "btn btn-primary" %></div>
        </div>
      <% end %>

      <hr class="border-b my-8" />

      <h3>Payment Method</h3>

      <% if current_team.card_type? %>
        <div class="flex">
          <div class="flex-1">
            <i class="fab fa-cc-<%= current_team.card_type.downcase %> text-gray-700"></i> <%= payment_method_details(current_team) %>
          </div>
          <div>
            <%= link_to "Update payment method", edit_card_path, class: "btn btn-link text-gray-700" %>
          </div>
        </div>

      <% else %>
        <p class="text-gray-700">You have no card on file.</p>
      <% end %>

      <hr class="border-b my-8" />

      <h3>Extra Billing Information</h3>
      <div class="flex items-center" data-controller="toggle">
        <div class="flex-1">
          <div class="text-gray-700">Add any additional information to all of your receipts such as your VAT ID, full business name, and address.</div>

          <%= form_with model: current_team, url: info_subscription_path, html: { class: "hidden mt-4", data: { target: "toggle.toggleable" }} do |f| %>
            <div class="form-group">
              <%= f.label :extra_billing_info %>
              <%= f.text_area :extra_billing_info, class: "form-control", placeholder: "VAT ID, Business name, address, etc..." %>
            </div>

            <div class="form-group">
              <%= f.button "Save Information", class: "btn btn-primary", data: { disable_with: disable_with("Saving...") } %>
            </div>
          <% end %>
        </div>

        <div>
          <%= link_to "Add information", "#", class: "btn btn-link text-gray-700", data: { action: "click->toggle#toggle" } %>
        </div>
      </div>
      <div class="text-gray-600">
        <%= current_team.extra_billing_info %>
      </div>

      <hr class="border-b my-8" />

      <h3>Invoices</h3>
      <p class="text-gray-700">Your history of transactions and payments.</p>

      <% if current_team.charges.exists? %>
        <table class="w-full">
          <thead>
            <tr>
              <th class="p-3 uppercase text-left text-xs text-gray-700">Date</th>
              <th class="p-3 uppercase text-left text-xs text-gray-700">Payment Method</th>
              <th class="p-3 uppercase text-left text-xs text-gray-700">Amount</th>
              <th class="p-3 uppercase text-left text-xs text-gray-700">Receipt</th>
            </tr>
          </thead>

          <tbody>
            <% current_team.charges.each do |charge| %>
              <tr class="group border-t border-gray-400 hover:bg-gray-200">
                <td class="p-3"><%= charge.created_at.strftime("%B %e, %Y") %></td>
                <td class="p-3"><i class="fab fa-cc-<%= charge.card_type.downcase %> text-gray-700"></i> <%= payment_method_details(charge) %></td>
                <td class="p-3"><%= number_to_currency charge.amount / 100.0 %></td>
                <td class="p-3"><%= link_to render_svg("icons/download"), charge_path(charge, format: :pdf) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>

      <% if current_team.subscription && !current_team.subscription.cancelled? %>
        <hr class="border-b my-8" />
        <h3>Cancel Your Subscription</h3>
        <div class="flex">
          <div class="flex-1 text-gray-700">
            <div class="font-bold">You can cancel anytime, but you'll lose access to <%= Jumpstart.config.application_name %>.</div>
            <div>Need to talk to someone? <%= mail_to Jumpstart.config.support_email, "Contact us", subject: "Question about #{Jumpstart.config.application_name}", class: "underline text-blue-600" %> -- we'd love to help.</div>
          </div>
          <div>
            <%= form_for current_team, url: subscription_url, method: :delete do |f| %>
              <%= f.button 'Cancel Subscription', class: "btn btn-link text-gray-700", data: { confirm: "Are you sure?", disable_with: disable_with("Cancelling..") } %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>